version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: Grant maven permission
          command: chmod +x mvnw
      - run:
          name: Get PROJECT_NAME && IMAGE_TAG
          command: |
            IMAGE_TAG=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout) 
            PROJECT_NAME=$(mvn help:evaluate -Dexpression=project.artifactId -q -DforceStdout)
            echo "$IMAGE_TAG"
            echo "$PROJECT_NAME"
      - setup_remote_docker:
          docker_layer_caching: false
          version: 18.06.0-ce
      - run:
          name: Build Docker image
          command: |
            IMAGE_NAME=$DOCKER_USER/$PROJECT_NAME
            docker build -t $IMAGE_NAME:$IMAGE_TAG .
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKER_USER" | docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"
            docker tag $IMAGE_NAME:$IMAGE_TAG $IMAGE_NAME:latest
            docker push $IMAGE_NAME:latest
            docker push $IMAGE_NAME:$IMAGE_TAG
workflows:
    version: 2
    build-master:
        jobs:
          - build:
              context: DOCKER
              filters:
                branches:
                  only: master